### PR TITLE
Version 3.0

### PR DESCRIPTION
**Pull request by J0hn5mith**

### CODE REVIEW

**Comment by philipplaeubli** [comment]
- Code LGTM
- please update the documentation as well!!! http://django-scarface.readthedocs.org/

**Comment by philipplaeubli** [comment]
assigning to @melbic for further review

**Comment by melbic** [comment]
h3. We'll have to rethink/process the following issues: 
- Compatible Migrations
- SNSCRUDMixin --> abstract
- delete vs deregister
- Replace trim_message
- remove unused code
- Extendability platforms
- Device-Platform-OS relationship
- Move platforms to settings?

**Comment by melbic** [comment]
Already merged,

**Pull request closed without merging**
